Feature/handle error
B3-3iL-DLW/3il-student pull request #78
Opened 2024-05-30 21:34 UTC by Yuta1409

- adds error handling 
- added translation with messages for different errors

2024-05-30 21:35 UTC, PHPLukaas commented
J'le fais pour toi 
Closes #65

2024-05-30 21:39 UTC, PHPLukaas reviewed
Enfin, félicitations Yan youhouu !

2024-05-31 11:18 UTC, julesartd requested changes
super, ajoute les traductions des messages d'erreurs dans le fichier anglais
app_en.arb

2024-05-31 11:18 UTC, julesartd commented on frontend/app_student/lib/l10n/app_fr.arb
super, cependant il faut que tu ajoutes la gestion des erreurs également dans le fichier anglais.

2024-06-01 18:44 UTC, merged